services:
  db:
    image: postgres:15
    container_name: CyberAware-db
    environment:
      POSTGRES_USER: cyber
      POSTGRES_PASSWORD: cyber
      POSTGRES_DB: CyberAware
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: